---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/workshops
  label: Workshops
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - workshop
- type: directory
  path: content/gallery
  label: Gallery
  create: all
  match: "**/*"
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
